title: Hours report
description: Accessability on the web
theme: just-the-docs

#logo: "/assets/images/logo.png"

url: https://chenpeleg.github.io/hours-report/


aux_links:
  View on GitHub: https://chenpeleg.github.io/hours-report/

callouts:
  warning:
    title: Warning
    color: red
  wrong:
    title: don't
    color: red
  right:
    title: do
    color: green
  important:
    title: Important
    color: purple
  
  
  
  
