name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check:
    name: Check files in docs folded
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != docs/* ]]; then
              echo "This modified file is not under the 'docs' folder." 
              echo "run_job=false" >> $GITHUB_OUTPUT
              break
            else 
              echo "run_job=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt


  # Build job
  build-jekyll:
    name: Build-jekyll if files in docs changed
    #    needs: check
    #    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Change and folders to match Jekyll structure
        run: |
          cp -r ./docs/site/build-jekyll-site.sh ./build-jekyll-site.sh
          chmod +x ./build-jekyll-site.sh
          ./build-jekyll-site.sh
          cp -r ./docs/site/. ./
        # needs to override the theme files again in cas of conflict
        shell: bash
      - name: Test files
        run: |
          cd ./docs
          echo "===== Docs ====="
          ls
          cd ..
          cd ./_posts
          echo "===== posts ====="
          ls
          cd ..
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site${{ steps.pages.outputs.base_path }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-jekyll
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
