name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ,18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: unzip files for the e2e test
        run: |
          unzip ./test/e2e/zip/*.zip -d ../
      - name: Check that the folders exist
        run: |
          cd ../
          ls
          cd accessibility
          echo "----- accessibility ---- "
          ls
      - name: try to run command
        run: |
          npm run start -- -o=./output -p=../accessibility -e=chenpeleg@gmail.com
      - run: npm run e2e
